site_name: "mkdocs UMA template"
site_url: https://jmgandarias.com/mkdoc_UMA_template
site_description: University of Málaga template to develop mkdocs websites. 
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font: 
    text: Source Sans Pro
    code: Source Code Pro
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: assets/logo_uma_blanco.png
  favicon: assets/logo_uma_blanco.svg

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
  
copyright: >
  &copy; <a href="https://jmgandarias.github.io">Juan M. Gandarias</a>, The University of Málaga, 2025 (License: <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC</a>)<br />
  <a href="#__consent">Change cookie settings</a>
repo_url: https://github.com/jmgandarias/mkdoc_UMA_template
repo_name: jmgandarias/mkdoc_UMA_template
edit_uri: ./edit/main/docs

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      enabled: !ENV [CI, false]
  - privacy:
      enabled: !ENV [CI, false]
  - redirects:
      redirect_maps:   
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: False
      video_loop: True
      video_autoplay: True
      css_style:
        width: "100%"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra:
  analytics:
    provider: google
    property: G-1SSCKMNFPR
  consent:
    title: Cookie consent
    description: 
      We use cookies to monitor the usage of these resources, and to understand 
      how effective they are in supporting your learning. Cookies also help us to 
      evaluate how much impact our teaching materials are making in the community.
      With your support, you are helping us to make our teaching resources better.